-- =============================================================================
-- JANA & DAS ENGINEERING PARTNERS - CLEAN SUPABASE SEED DATA
-- Initial firm profile, roles, partners, and equity. No passwords: partners
-- sign in through Supabase Auth. Re-running never overwrites existing rows.
-- =============================================================================

-- Data for agency_profile (1 rows)
INSERT INTO public.agency_profile ("id", "name", "tagline", "email", "phone", "website", "address", "cityStateZip", "country", "taxId", "defaultCurrency", "currencySymbol", "bankDetails", "primarySigner", "updatedAt") VALUES ('firm-profile-1', 'Jana & Das Engineering Partners', 'Specialized Software Engineering, Systems Architecture & Digital Products', 'contact@janadas.agency', '+91 98765 43210', 'https://janadas.agency', 'Tech Park Gateway, Sector V', 'Kolkata, WB 700091', 'India', 'IN-GSTIN-19AAEFJ9024K1Z8', 'USD', '$', '{"bankName": "HDFC Commercial Banking", "accountHolder": "Jana and Das Engineering Partners", "accountNumber": "50200084920194", "routingOrSwift": "HDFCINBB", "iban": "IN92HDFC00050200084920194", "notes": "NEFT / RTGS / Swift wire remittance preferred. Reference invoice number."}'::jsonb, '{"name": "Subhadip Jana", "title": "Senior Managing Partner", "email": "subhadipjana@jdtensor.com", "signatureText": "Subhadip Jana", "signatureImage": "data:image/svg+xml;utf8,<svg xmlns=''http://www.w3.org/2000/svg'' viewBox=''0 0 320 80'' width=''320'' height=''80''><path d=''M25,52 C35,20 42,10 50,26 C56,38 62,56 68,54 C76,52 82,34 90,32 C98,30 102,46 110,44 C120,40 130,22 142,36 C150,45 158,55 168,48 C178,42 186,28 196,30 C208,32 214,48 228,42 C240,36 250,20 262,38 C270,50 282,54 298,32'' fill=''none'' stroke=''%230f172a'' stroke-width=''3'' stroke-linecap=''round'' stroke-linejoin=''round''/><path d=''M35,62 C90,56 180,50 275,46'' fill=''none'' stroke=''%230f172a'' stroke-width=''2'' stroke-linecap=''round''/></svg>"}'::jsonb, '2026-09-14T15:53:36.857416Z') ON CONFLICT ("id") DO NOTHING;

-- Data for custom_roles (6 rows)
INSERT INTO public.custom_roles ("id", "name", "description", "level", "isSystem", "permissions", "createdAt") VALUES ('role-partner', 'partner', 'Founding Partner with unrestricted governance, equity, financial authority, and full role administration.', 100, true, '{"manage_firm_equity": true, "manage_roles": true, "manage_contracts": true, "manage_invoices": true, "manage_payments": true, "manage_expenses": true, "manage_ip": true, "manage_assets": true, "manage_debts": true, "manage_taxes": true, "manage_team": true, "manage_clients": true, "manage_tasks": true, "create_documents": true}'::jsonb, '2026-09-14T15:53:36.857416Z') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.custom_roles ("id", "name", "description", "level", "isSystem", "permissions", "createdAt") VALUES ('role-admin', 'admin', 'Operations administrator. Manages invoices, expenses, team, clients, and role assignments below admin.', 80, true, '{"manage_firm_equity": false, "manage_roles": true, "manage_contracts": true, "manage_invoices": true, "manage_payments": true, "manage_expenses": true, "manage_ip": true, "manage_assets": true, "manage_debts": true, "manage_taxes": false, "manage_team": true, "manage_clients": true, "manage_tasks": true, "create_documents": true}'::jsonb, '2026-09-14T15:53:36.857416Z') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.custom_roles ("id", "name", "description", "level", "isSystem", "permissions", "createdAt") VALUES ('role-manager', 'manager', 'Project & Client delivery lead. Oversees contracts, clients, tasks, and team assignments below manager.', 60, true, '{"manage_firm_equity": false, "manage_roles": true, "manage_contracts": true, "manage_invoices": false, "manage_payments": false, "manage_expenses": false, "manage_ip": false, "manage_assets": false, "manage_debts": false, "manage_taxes": false, "manage_team": true, "manage_clients": true, "manage_tasks": true, "create_documents": true}'::jsonb, '2026-09-14T15:53:36.857416Z') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.custom_roles ("id", "name", "description", "level", "isSystem", "permissions", "createdAt") VALUES ('role-developer', 'developer', 'Engineering contributor. Builds software features, works on assigned tasks, and logs code deliverables.', 40, true, '{"manage_firm_equity": false, "manage_roles": false, "manage_contracts": false, "manage_invoices": false, "manage_payments": false, "manage_expenses": false, "manage_ip": false, "manage_assets": false, "manage_debts": false, "manage_taxes": false, "manage_team": false, "manage_clients": false, "manage_tasks": true, "create_documents": false}'::jsonb, '2026-09-14T15:53:36.857416Z') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.custom_roles ("id", "name", "description", "level", "isSystem", "permissions", "createdAt") VALUES ('role-designer', 'designer', 'Creative design contributor. Delivers UX specifications, design systems, and visual assets.', 40, true, '{"manage_firm_equity": false, "manage_roles": false, "manage_contracts": false, "manage_invoices": false, "manage_payments": false, "manage_expenses": false, "manage_ip": false, "manage_assets": false, "manage_debts": false, "manage_taxes": false, "manage_team": false, "manage_clients": false, "manage_tasks": true, "create_documents": false}'::jsonb, '2026-09-14T15:53:36.857416Z') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.custom_roles ("id", "name", "description", "level", "isSystem", "permissions", "createdAt") VALUES ('role-auditor', 'auditor', 'Compliance and financial auditor. Comprehensive read-only inspection of all ledgers, taxes, equity, and contracts.', 30, true, '{"manage_firm_equity": false, "manage_roles": false, "manage_contracts": false, "manage_invoices": false, "manage_payments": false, "manage_expenses": false, "manage_ip": false, "manage_assets": false, "manage_debts": false, "manage_taxes": false, "manage_team": false, "manage_clients": false, "manage_tasks": false, "create_documents": false}'::jsonb, '2026-09-14T15:53:36.857416Z') ON CONFLICT ("id") DO NOTHING;

-- Data for users (2 rows)
INSERT INTO public.users ("id", "name", "email", "avatarUrl", "role", "roleLevel", "status", "paymentType", "paymentAmount", "currency", "skills", "joinedDate", "username", "accessLevel", "mustChangePassword", "notes") VALUES ('usr-subhadip', 'Subhadip Jana', 'subhadipjana@jdtensor.com', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256', 'Senior Managing Partner', 100, 'active', 'fixed', 0.0, 'USD', '["Systems Architecture", "Distributed Infrastructure", "Partnership Governance", "Product Engineering"]'::jsonb, '2025-01-01', 'subhadip866', 'admin', false, 'Co-founding Senior Managing Partner') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.users ("id", "name", "email", "avatarUrl", "role", "roleLevel", "status", "paymentType", "paymentAmount", "currency", "skills", "joinedDate", "username", "accessLevel", "mustChangePassword", "notes") VALUES ('usr-shayan', 'Shayan Das', 'shayandas@jdtensor.com', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256', 'Senior Managing Partner', 100, 'active', 'fixed', 0.0, 'USD', '["Product Design", "Commercial Strategy", "Engineering Leadership", "Client Partnerships"]'::jsonb, '2025-01-01', 'shayan267', 'admin', false, 'Co-founding Senior Managing Partner') ON CONFLICT ("id") DO NOTHING;

-- Data for partner_equity (2 rows)
INSERT INTO public.partner_equity ("partnerId", "partnerName", "designation", "email", "ownershipPercentage", "profitSharePercentage", "initialCapitalContribution", "totalContributed", "totalDrawings", "netCapitalBalance", "signatureImage", "lastUpdated") VALUES ('usr-subhadip', 'Subhadip Jana', 'Senior Managing Partner', 'subhadipjana@jdtensor.com', 50.0, 50.0, 0.0, 0.0, 0.0, 0.0, 'data:image/svg+xml;utf8,<svg xmlns=''http://www.w3.org/2000/svg'' viewBox=''0 0 320 80'' width=''320'' height=''80''><path d=''M25,52 C35,20 42,10 50,26 C56,38 62,56 68,54 C76,52 82,34 90,32 C98,30 102,46 110,44 C120,40 130,22 142,36 C150,45 158,55 168,48 C178,42 186,28 196,30 C208,32 214,48 228,42 C240,36 250,20 262,38 C270,50 282,54 298,32'' fill=''none'' stroke=''%230f172a'' stroke-width=''3'' stroke-linecap=''round'' stroke-linejoin=''round''/><path d=''M35,62 C90,56 180,50 275,46'' fill=''none'' stroke=''%230f172a'' stroke-width=''2'' stroke-linecap=''round''/></svg>', '2026-09-14T15:53:36.857416Z') ON CONFLICT ("partnerId") DO NOTHING;
INSERT INTO public.partner_equity ("partnerId", "partnerName", "designation", "email", "ownershipPercentage", "profitSharePercentage", "initialCapitalContribution", "totalContributed", "totalDrawings", "netCapitalBalance", "signatureImage", "lastUpdated") VALUES ('usr-shayan', 'Shayan Das', 'Senior Managing Partner', 'shayandas@jdtensor.com', 50.0, 50.0, 0.0, 0.0, 0.0, 0.0, 'data:image/svg+xml;utf8,<svg xmlns=''http://www.w3.org/2000/svg'' viewBox=''0 0 320 80'' width=''320'' height=''80''><path d=''M30,45 C45,25 55,20 70,35 C80,48 90,55 105,40 C120,25 135,20 150,38 C165,52 175,60 190,45 C205,30 220,25 240,40 C255,50 270,52 285,35'' fill=''none'' stroke=''%230f172a'' stroke-width=''3'' stroke-linecap=''round'' stroke-linejoin=''round''/><path d=''M40,65 C100,58 190,52 280,48'' fill=''none'' stroke=''%230f172a'' stroke-width=''2'' stroke-linecap=''round''/></svg>', '2026-09-14T15:53:36.857416Z') ON CONFLICT ("partnerId") DO NOTHING;

-- Link partner rows to Supabase Auth accounts that were created before this
-- seed ran. Accounts created later are linked automatically by a trigger.
UPDATE public.users u SET auth_user_id = au.id
FROM auth.users au
WHERE u.auth_user_id IS NULL
  AND au.email_confirmed_at IS NOT NULL
  AND lower(au.email) = lower(u.email);
